name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install shellcheck-py yamllint
    
    - name: Lint shell scripts
      run: |
        find . -type f -name "*.sh" -exec shellcheck {} \;
    
    - name: Lint YAML files
      run: |
        yamllint .
    
    - name: Check script permissions
      run: |
        if find ./scripts -type f -name "*.sh" ! -perm -u=x; then
          echo "Error: Some shell scripts are not executable"
          exit 1
        fi

  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Test Homebrew installation script
      run: |
        ./scripts/install-homebrew-minimal.sh --dry-run || true
    
    - name: Validate Brewfile
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        brew bundle check --file=scripts/Brewfile || true 